name: Basicis | CI Workflow
on:
  pull_request:
    branchs: 
      - [dev]
jobs:
  test_and_build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout âœ”
        uses: actions/checkout@v2

      - name: Composer ğŸ”§
        uses: php-actions/composer@v1

      - name: PHPUnit Tests ğŸ§ª
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/test.sh

      - name: Run Documentation Build ğŸ› ï¸
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/deploy.sh
          
  deploy:
    runs-on: ubuntu-18.04
    needs: test_and_build
    steps:
      - name: Checkout âœ”
        uses: actions/checkout@v2

      - name: Deploy Documentation on Github Pages  ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: $GITHUB_WORKSPACE/docs/ 
          CLEAN: true